{
"distance":0.43,
"id":3341,
"displayName":"Dallas Neighborhood Market",
"storeType":{
"id":"4",
"displayName":"Neighborhood Market",
},
"address":{
"postalCode":"75204",
"address":"2305 N Central Expy",
"city":"Dallas",
"state":"TX",
"country":"US"
},
"operationalHours":{
"open24Hours":NULL
}
}